name: Dump Entities from Baserow

on:
  schedule:
  - cron: "13 */12 * * *"
  workflow_dispatch:

jobs:
  download:
    name: dump baserow
    runs-on: ubuntu-latest
    env:
      BASEROW_TOKEN: ${{secrets.BASEROW_TOKEN}}
      BASEROW_USER: ${{secrets.BASEROW_USER}}
      BASEROW_PW: ${{secrets.BASEROW_PW}}
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install py requirements, dump and denormalize data
        run: |
          pip install -U pip
          pip install -r scripts/python/requirements.txt
          python scripts/python/dump_data.py
          python scripts/python/denormalize.py
      - name: data dump to xml
        run: |
          python scripts/python/json2xml.py
      - name: create pmb beacon
        run: |
          python scripts/python/pmb-beacon-generator.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Downloaded/Updated Data
