name: Dump Entities from Baserow

on:
  schedule:
  - cron: "13 */12 * * *"
  workflow_dispatch:

jobs:
  download:
    name: dump baserow
    runs-on: ubuntu-latest
    env:
      BASEROW_TOKEN: ${{secrets.BASEROW_TOKEN}}
      BASEROW_USER: ${{secrets.BASEROW_USER}}
      BASEROW_PW: ${{secrets.BASEROW_PW}}
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v3
      - name: isntall py dump denormalize data
        run: |
          pip install -r requirements.txt
          python dump_data.py
          python download_zotero.py
          python denormalize.py
      - name: data dump to xml
        run: |
          python json2xml.py
      - name: create pmb beacon
        run: |
          python pmb-beacon-generator.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Downloaded/Updated Data
